### ISSUE TITLE
BoundsError

### ISSUE THREAD

**Issue by tyler-peirce** [ian-small/Emma#5]
Hi Ian,
I have received the BoundsError on a few of the mitogenomes I have been processing. The mitogenomes had a successful assembly using GetOrganelle and were circularised. Please see the error output below:

    Command error:
      [ Info: OG825.ilmn.240716.getorg1770.fasta
      [ Info: OG825.ilmn.240716.getorg1770	16587 bp
      [ Info: found 22 tRNA genes
      [ Info: COX2.protein
      [ Info: ATP8.protein
      [ Info: ATP6.protein
      [ Info: COX3.protein
      [ Info: ND3.protein
      [ Info: ND4L.protein
      [ Info: ND4.protein
      [ Info: ND5.protein
      [ Info: CYTB.protein
      [ Info: ND1.protein
      [ Info: ND2.protein
      [ Info: COX1.protein
      ┌ Error: "OG825.ilmn.240716.getorg1770" failed! BoundsError(Vector{Int32}[[19, 55, 172, 301, 355, 361, 373, 376, 391, 439, 496, 592, 601, 631, 661, 691, 712, 799, 811, 835, 919, 937, 991, 997, 1003, 1018, 1105, 1168, 1207, 1240, 1270, 1279, 1303, 1417, 1510, 1519, 1591, 1597, 1627, 1657, 1687, 1720, 1765, 1897, 1933, 1939, 1957, 1981, 1984, 2008, 2077, 2089, 2134, 2149, 2854, 2884, 2932, 2935, 2983, 2989, 3010, 3046, 3103, 3139, 3190, 3226, 3280, 3310, 3343, 3349, 3361, 3391, 3451, 3520, 3589, 3640, 3694, 3703, 3802, 3847, 3946, 3949, 4000, 4042, 4048, 4060, 4069, 4171, 4228, 4237, 4282, 4363, 4366, 4480, 4531, 4564, 4597, 4681, 4831, 4843, 4888, 5014, 5038, 5101, 5137, 5140, 5173, 5188, 5224, 5239, 5305, 5317, 5320, 5353, 5413, 5461, 5518, 5551, 5554, 5581, 5611, 5617, 5671, 5719, 5770, 5788, 5797, 5800, 5803, 5809, 5827, 5854, 5872, 5887, 5953, 5959, 5962, 6019, 6043, 6049, 6061, 6082, 6106, 6148, 6160, 6247, 6328, 6343, 6382, 6406, 6424, 6433, 6436, 6481, 6571, 6586, 6598, 6607, 6691, 6697, 6754, 6799, 6823, 6832, 6844, 6865, 6892, 6943, 6973, 6979, 6982, 6985, 7000, 7015, 7120, 7162, 7201, 7255, 7321, 7414, 7444, 7459, 7468, 7501, 7516, 7531, 7549, 7564, 7624, 7666, 7678, 7720, 7729, 7765, 7801, 7825, 7948, 7978, 8017, 8047, 8122, 8212, 8233, 8320, 8362, 8383, 8455, 8488, 8509, 8578, 8608, 8674, 8788, 8821, 8830, 8842, 8965, 8980, 9019, 9145, 9181, 9205, 9319, 9331, 9340, 9352, 9415, 9439, 9451, 9454, 9484, 9502, 9544, 9559, 9586, 9598, 9652, 9664, 9682, 9688, 9715, 9727, 9769, 9772, 9826, 9838, 9847, 9874, 9967, 9976, 9979, 10045, 10057, 10081, 10105, 10183, 10213, 10327, 10450, 10459, 10486, 10504, 10549, 10618, 10630, 10642, 10651, 10657, 10669, 10672, 10720, 10789, 10852, 10876, 10915, 10954, 10969, 10981, 10984, 11002, 11050, 11119, 11200, 11227, 11332, 11383, 11395, 11419, 11461, 11485, 11491, 11572, 11596, 11614, 11644, 11761, 11812, 11830, 11848, 11863, 11914, 11995, 12019, 12022, 12025, 12124, 12193, 12205, 12229, 12244, 12322, 12424, 12439, 12472, 12502, 12520, 12586, 12604, 12616, 12694, 12751, 12754, 12781, 12799, 12865, 12880, 12883, 12907, 12925, 13027, 13042, 13063, 13117, 13141, 13186, 13195, 13213, 13267, 13369, 13414, 13426, 13462, 14473, 14482, 14515, 14524, 14554, 14584, 14623, 14635, 14668, 15736, 15736, 15745, 15757, 15763, 15820, 15853, 15865, 15880, 15889, 15922, 16021, 16069, 16213, 16216, 16237, 16252, 16297, 16321, 16324, 16336, 16339, 16384, 16387, 16405, 16468, 16483, 16525, 16537, 16585], [2, 20, 29, 50, 176, 221, 332, 338, 356, 392, 440, 506, 539, 545, 593, 605, 620, 632, 692, 800, 806, 836, 866, 875, 962, 1019, 1061, 1097, 1166, 1169, 1223, 1940, 1946, 1952, 1976, 1982, 2180, 2201, 2216, 2228, 2243, 2288, 2303, 2363, 2390, 2399, 2402, 2411, 2420, 2429, 2480, 2504, 2513, 2549, 2585, 2597, 2642, 2654, 2666, 2684, 2693, 2726, 2738, 2756, 2762, 2771, 2780, 2798, 2843, 2912, 2942, 2990, 3032, 3044, 3059, 3086, 3122, 3140, 3191, 3194, 3212, 3227, 3275, 3311, 3314, 3362, 3392, 3422, 3590, 3632, 3641, 3665, 4061, 4061, 4112, 4172, 4181, 4229, 4232, 4349, 5801, 5804, 5828, 5846, 5849, 5870, 5873, 5945, 5954, 5966, 5987, 6125, 6179, 6206, 6212, 6218, 6269, 6281, 6344, 6473, 6476, 6482, 6527, 6572, 6575, 6614, 6620, 6629, 6656, 6659, 6707, 6755, 6758, 6809, 6845, 6851, 6974, 7106, 7121, 7124, 7187, 7205, 7217, 7220, 7355, 7421, 7454, 7532, 7550, 7580, 7625, 7661, 7679, 7721, 7730, 7736, 7754, 7793, 7889, 7907, 7919, 7925, 7931, 7970, 8042, 8087, 8093, 8147, 8153, 8225, 8237, 8255, 8288, 8294, 8309, 8312, 8321, 8597, 8627, 8696, 8708, 8756, 8783, 8786, 8843, 8861, 8879, 8927, 8951, 8966, 8969, 9065, 9089, 9095, 9101, 9104, 9137, 9146, 9206, 9209, 9215, 9233, 9260, 9320, 9446, 9473, 9485, 9563, 9572, 9578, 9596, 9602, 9605, 9611, 9617, 9677, 9680, 9701, 9722, 9779, 9794, 9824, 9872, 9896, 9935, 9947, 10034, 10055, 10100, 10277, 10307, 10457, 10532, 10574, 10616, 10625, 10691, 10802, 10838, 10901, 10994, 11009, 11027, 11120, 11138, 11144, 11210, 11228, 11237, 11240, 11261, 11372, 11378, 11462, 11465, 11468, 11474, 11480, 11492, 11567, 11582, 11591, 11606, 11627, 11645, 11684, 11687, 11738, 11753, 11765, 11825, 11888, 11912, 12011, 12026, 12071, 12074, 12095, 12098, 12101, 12125, 12173, 12182, 12191, 12245, 12248, 12272, 12275, 12296, 12437, 12461, 12518, 12599, 12608, 12677, 12692, 12854, 12866, 12875, 12899, 12938, 13055, 13079, 13142, 13307, 13316, 13328, 13331, 13424, 13457, 13478, 13538, 13562, 13583, 13601, 13736, 13760, 13805, 13811, 13817, 13835, 13850, 13868, 13904, 13925, 13955, 13961, 13970, 14060, 14087, 14093, 14117, 14138, 14156, 14216, 14219, 14294, 14297, 14372, 14381, 14411, 14483, 14516, 14534, 14558, 14561, 14582, 14597, 14621, 14621, 14669, 14690, 14735, 14774, 14783, 14789, 14804, 14822, 14873, 14981, 14984, 14990, 15002, 15 12907, 12925, 13027, 13042, 13063, 13117, 13141, 13186, 13195, 13213, 13267, 13369, 13414, 13426, 13462, 14473, 14482, 14515, 14524, 14554, 14584, 14623, 14635, 14668, 15736, 15736, 15745, 15757, 15763, 15820, 15853, 15865, 15880, 15889, 15922, 16021, 16069, 16213, 16216, 16237, 16252, 16297, 16321, 16324, 16336, 16339, 16384, 16387, 16405, 16468, 16483, 16525, 16537, 16585], [2, 20, 29, 50, 176, 221, 332, 338, 356, 392, 440, 506, 539, 545, 593, 605, 620, 632, 692, 800, 806, 836, 866, 875, 962, 1019, 1061, 1097, 1166, 1169, 1223, 1940, 1946, 1952, 1976, 1982, 2180, 2201, 2216, 2228, 2243, 2288, 2303, 2363, 2390, 2399, 2402, 2411, 2420, 2429, 2480, 2504, 2513, 2549, 2585, 2597, 2642, 2654, 2666, 2684, 2693, 2726, 2738, 2756, 2762, 2771, 2780, 2798, 2843, 2912, 2942, 2990, 3032, 3044, 3059, 3086, 3122, 3140, 3191, 3194, 3212, 3227, 3275, 3311, 3314, 3362, 3392, 3422, 3590, 3632, 3641, 3665, 4061, 4061, 4112, 4172, 4181, 4229, 4232, 4349, 5801, 5804, 5828, 5846, 5849, 5870, 5873, 5945, 5954, 5966, 5987, 6125, 6179, 6206, 6212, 6218, 6269, 6281, 6344, 6473, 6476, 6482, 6527, 6572, 6575, 6614, 6620, 6629, 6656, 6659, 6707, 6755, 6758, 6809, 6845, 6851, 6974, 7106, 7121, 7124, 7187, 7205, 7217, 7220, 7355, 7421, 7454, 7532, 7550, 7580, 7625, 7661, 7679, 7721, 7730, 7736, 7754, 7793, 7889, 7907, 7919, 7925, 7931, 7970, 8042, 8087, 8093, 8147, 8153, 8225, 8237, 8255, 8288, 8294, 8309, 8312, 8321, 8597, 8627, 8696, 8708, 8756, 8783, 8786, 8843, 8861, 8879, 8927, 8951, 8966, 8969, 9065, 9089, 9095, 9101, 9104, 9137, 9146, 9206, 9209, 9215, 9233, 9260, 9320, 9446, 9473, 9485, 9563, 9572, 9578, 9596, 9602, 9605, 9611, 9617, 9677, 9680, 9701, 9722, 9779, 9794, 9824, 9872, 9896, 9935, 9947, 10034, 10055, 10100, 10277, 10307, 10457, 10532, 10574, 10616, 10625, 10691, 10802, 10838, 10901, 10994, 11009, 11027, 11120, 11138, 11144, 11210, 11228, 11237, 11240, 11261, 11372, 11378, 11462, 11465, 11468, 11474, 11480, 11492, 11567, 11582, 11591, 11606, 11627, 11645, 11684, 11687, 11738, 11753, 11765, 11825, 11888, 11912, 12011, 12026, 12071, 12074, 12095, 12098, 12101, 12125, 12173, 12182, 12191, 12245, 12248, 12272, 12275, 12296, 12437, 12461, 12518, 12599, 12608, 12677, 12692, 12854, 12866, 12875, 12899, 12938, 13055, 13079, 13142, 13307, 13316, 13328, 13331, 13424, 13457, 13478, 13538, 13562, 13583, 13601, 13736, 13760, 13805, 13811, 13817, 13835, 13850, 13868, 13904, 13925, 13955, 13961, 13970, 14060, 14087, 14093, 14117, 14138, 14156, 14216, 14219, 14294, 14297, 14372, 14381, 14411, 14483, 14516, 14534, 14558, 14561, 14582, 14597, 14621, 14621, 14669, 14690, 14735, 14774, 14783, 14789, 14804, 14822, 14873, 14981, 14984, 14990, 15002, 15056, 15062, 15179, 15224, 15248, 15257, 15287, 15314, 15320, 15350, 15440, 15458, 15482, 15497, 15512, 15530, 15539, 15551, 15575, 15614, 15680, 15716, 15737, 15746, 15779, 15812, 15827, 15881, 15911, 15950, 15965, 15968, 15971, 15977, 15980, 16001, 16022, 16034, 16064, 16067, 16109, 16160, 16169, 16217, 16262, 16424, 16484, 16532, 16547], [1092, 1101, 1167, 1170, 1176, 1179, 1269, 1296, 1332, 1335, 1359, 1398, 1416, 1425, 1461, 1506, 1509, 1596, 1614, 1632, 1656, 1674, 1677, 1686, 1764, 1785, 1878, 1896, 1923, 1941, 1944, 1956, 1962, 1968, 2076, 2097, 2100, 2142, 2148, 2217, 2292, 2364, 2373, 2430, 2475, 2481, 2538, 2550, 2565, 2568, 2616, 2643, 2661, 2781, 3639, 3639, 3648, 3654, 3708, 3711, 3720, 3765, 3792, 3795, 3846, 3999, 4020, 4038, 4047, 4062, 4062, 4065, 4074, 4425, 4452, 4470, 4515, 4545, 4590, 4620, 4647, 4650, 4656, 4719, 4746, 4767, 4782, 4812, 4884, 4905, 5025, 5109, 5130, 5136, 5151, 5160, 5172, 5208, 5229, 5235, 5277, 5295, 5304, 5313, 5316, 5328, 5361, 5370, 5385, 5409, 5454, 5484, 5487, 5550, 5559, 5562, 5601, 5607, 5658, 5661, 5730, 5781, 5802, 5847, 5853, 5871, 5877, 5886, 5904, 5952, 5988, 7863, 7875, 7926, 8013, 8070, 8208, 8214, 8220, 8307, 8358, 8406, 8448, 9597, 9618, 9633, 9648, 9675, 9714, 9786, 9807, 9831, 9954, 9972, 10167, 10218, 10227, 10275, 10308, 10332, 10341, 10368, 10389, 10410, 10422, 10428, 10521, 10596, 10605, 10611, 10617, 10635, 10659, 10758, 10869, 10884, 10911, 10923, 10956, 10992, 10998, 11052, 11103, 11154, 11238, 11340, 11343, 11400, 11427, 11643, 11652, 11664, 11697, 11727, 11847, 11850, 11946, 11967, 11976, 12051, 12060, 12072, 12198, 12255, 12294, 12312, 12330, 12351, 12441, 12540, 12549, 12597, 12612, 12618, 12621, 12690, 12723, 12774, 12804, 12873, 12900, 12912, 12918, 12945, 12954, 12993, 13059, 13080, 13116, 13122, 13158, 13215, 13236, 13260, 13275, 13326, 13383, 13389, 13425, 13437, 13476, 13602, 13623, 13668, 13677, 13689, 13692, 13806, 13818, 13869, 13875, 13956, 13992, 14013, 14025, 14091, 14097, 14124, 14133, 14145, 14151, 14157, 14166, 14169, 14196, 14205, 14481, 14502, 14529, 14553, 14622, 14625, 14673, 14736, 14784, 14790, 14796, 14886, 14910, 14943, 15051, 15057, 15069, 15135, 15180, 15183, 15189, 15198, 15249, 15369, 15441, 15444, 15462, 15492, 15507, 15609, 15618, 15738, 15738, 15750, 15810, 15861, 15870, 15885, 15915, 15981, 16008, 16041, 16062]], (0,))
      └ @ Emma /opt/Emma/src/cmd.jl:115

This happened on 3 out of 51 of the samples that i ran through EMMA.
Is there a way to troubleshoot this error?
Thanks, Tyler

**Comment by ian-small** [comment]
Hi Tyler,
Do the same files fail every time, or is it just a random few files every run? If the former, can you share the problematic input files so I can run some tests?
If you don’t want to do that, can you run Emma in debug mode? (add ‘--loglevel debug’ to the options)
Cheers
Ian

From: tyler-peirce ***@***.***>
Date: Friday, 8 November 2024 at 10:43 am
To: ian-small/Emma ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ian-small/Emma] BoundsError (Issue #5)

Hi Ian,
I have received the BoundsError on a few of the mitogenomes I have been processing. The mitogenomes had a successful assembly using GetOrganelle and were circularised. Please see the error output below:

Command error:

  [ Info: OG825.ilmn.240716.getorg1770.fasta

  [ Info: OG825.ilmn.240716.getorg1770 16587 bp

  [ Info: found 22 tRNA genes

  [ Info: COX2.protein

  [ Info: ATP8.protein

  [ Info: ATP6.protein

  [ Info: COX3.protein

  [ Info: ND3.protein

  [ Info: ND4L.protein

  [ Info: ND4.protein

  [ Info: ND5.protein

  [ Info: CYTB.protein

  [ Info: ND1.protein

  [ Info: ND2.protein

  [ Info: COX1.protein

  ┌ Error: "OG825.ilmn.240716.getorg1770" failed! BoundsError(Vector{Int32}[[19, 55, 172, 301, 355, 361, 373, 376, 391, 439, 496, 592, 601, 631, 661, 691, 712, 799, 811, 835, 919, 937, 991, 997, 1003, 1018, 1105, 1168, 1207, 1240, 1270, 1279, 1303, 1417, 1510, 1519, 1591, 1597, 1627, 1657, 1687, 1720, 1765, 1897, 1933, 1939, 1957, 1981, 1984, 2008, 2077, 2089, 2134, 2149, 2854, 2884, 2932, 2935, 2983, 2989, 3010, 3046, 3103, 3139, 3190, 3226, 3280, 3310, 3343, 3349, 3361, 3391, 3451, 3520, 3589, 3640, 3694, 3703, 3802, 3847, 3946, 3949, 4000, 4042, 4048, 4060, 4069, 4171, 4228, 4237, 4282, 4363, 4366, 4480, 4531, 4564, 4597, 4681, 4831, 4843, 4888, 5014, 5038, 5101, 5137, 5140, 5173, 5188, 5224, 5239, 5305, 5317, 5320, 5353, 5413, 5461, 5518, 5551, 5554, 5581, 5611, 5617, 5671, 5719, 5770, 5788, 5797, 5800, 5803, 5809, 5827, 5854, 5872, 5887, 5953, 5959, 5962, 6019, 6043, 6049, 6061, 6082, 6106, 6148, 6160, 6247, 6328, 6343, 6382, 6406, 6424, 6433, 6436, 6481, 6571, 6586, 6598, 6607, 6691, 6697, 6754, 6799, 6823, 6832, 6844, 6865, 6892, 6943, 6973, 6979, 6982, 6985, 7000, 7015, 7120, 7162, 7201, 7255, 7321, 7414, 7444, 7459, 7468, 7501, 7516, 7531, 7549, 7564, 7624, 7666, 7678, 7720, 7729, 7765, 7801, 7825, 7948, 7978, 8017, 8047, 8122, 8212, 8233, 8320, 8362, 8383, 8455, 8488, 8509, 8578, 8608, 8674, 8788, 8821, 8830, 8842, 8965, 8980, 9019, 9145, 9181, 9205, 9319, 9331, 9340, 9352, 9415, 9439, 9451, 9454, 9484, 9502, 9544, 9559, 9586, 9598, 9652, 9664, 9682, 9688, 9715, 9727, 9769, 9772, 9826, 9838, 9847, 9874, 9967, 9976, 9979, 10045, 10057, 10081, 10105, 10183, 10213, 10327, 10450, 10459, 10486, 10504, 10549, 10618, 10630, 10642, 10651, 10657, 10669, 10672, 10720, 10789, 10852, 10876, 10915, 10954, 10969, 10981, 10984, 11002, 11050, 11119, 11200, 11227, 11332, 11383, 11395, 11419, 11461, 11485, 11491, 11572, 11596, 11614, 11644, 11761, 11812, 11830, 11848, 11863, 11914, 11995, 12019, 12022, 12025, 12124, 12193, 12205, 12229, 12244, 12322, 12424, 12439, 12472, 12502, 12520, 12586, 12604, 12616, 12694, 12751, 12754, 12781, 12799, 12865, 12880, 12883, 12907, 12925, 13027, 13042, 13063, 13117, 13141, 13186, 13195, 13213, 13267, 13369, 13414, 13426, 13462, 14473, 14482, 14515, 14524, 14554, 14584, 14623, 14635, 14668, 15736, 15736, 15745, 15757, 15763, 15820, 15853, 15865, 15880, 15889, 15922, 16021, 16069, 16213, 16216, 16237, 16252, 16297, 16321, 16324, 16336, 16339, 16384, 16387, 16405, 16468, 16483, 16525, 16537, 16585], [2, 20, 29, 50, 176, 221, 332, 338, 356, 392, 440, 506, 539, 545, 593, 605, 620, 632, 692, 800, 806, 836, 866, 875, 962, 1019, 1061, 1097, 1166, 1169, 1223, 1940, 1946, 1952, 1976, 1982, 2180, 2201, 2216, 2228, 2243, 2288, 2303, 2363, 2390, 2399, 2402, 2411, 2420, 2429, 2480, 2504, 2513, 2549, 2585, 2597, 2642, 2654, 2666, 2684, 2693, 2726, 2738, 2756, 2762, 2771, 2780, 2798, 2843, 2912, 2942, 2990, 3032, 3044, 3059, 3086, 3122, 3140, 3191, 3194, 3212, 3227, 3275, 3311, 3314, 3362, 3392, 3422, 3590, 3632, 3641, 3665, 4061, 4061, 4112, 4172, 4181, 4229, 4232, 4349, 5801, 5804, 5828, 5846, 5849, 5870, 5873, 5945, 5954, 5966, 5987, 6125, 6179, 6206, 6212, 6218, 6269, 6281, 6344, 6473, 6476, 6482, 6527, 6572, 6575, 6614, 6620, 6629, 6656, 6659, 6707, 6755, 6758, 6809, 6845, 6851, 6974, 7106, 7121, 7124, 7187, 7205, 7217, 7220, 7355, 7421, 7454, 7532, 7550, 7580, 7625, 7661, 7679, 7721, 7730, 7736, 7754, 7793, 7889, 7907, 7919, 7925, 7931, 7970, 8042, 8087, 8093, 8147, 8153, 8225, 8237, 8255, 8288, 8294, 8309, 8312, 8321, 8597, 8627, 8696, 8708, 8756, 8783, 8786, 8843, 8861, 8879, 8927, 8951, 8966, 8969, 9065, 9089, 9095, 9101, 9104, 9137, 9146, 9206, 9209, 9215, 9233, 9260, 9320, 9446, 9473, 9485, 9563, 9572, 9578, 9596, 9602, 9605, 9611, 9617, 9677, 9680, 9701, 9722, 9779, 9794, 9824, 9872, 9896, 9935, 9947, 10034, 10055, 10100, 10277, 10307, 10457, 10532, 10574, 10616, 10625, 10691, 10802, 10838, 10901, 10994, 11009, 11027, 11120, 11138, 11144, 11210, 11228, 11237, 11240, 11261, 11372, 11378, 11462, 11465, 11468, 11474, 11480, 11492, 11567, 11582, 11591, 11606, 11627, 11645, 11684, 11687, 11738, 11753, 11765, 11825, 11888, 11912, 12011, 12026, 12071, 12074, 12095, 12098, 12101, 12125, 12173, 12182, 12191, 12245, 12248, 12272, 12275, 12296, 12437, 12461, 12518, 12599, 12608, 12677, 12692, 12854, 12866, 12875, 12899, 12938, 13055, 13079, 13142, 13307, 13316, 13328, 13331, 13424, 13457, 13478, 13538, 13562, 13583, 13601, 13736, 13760, 13805, 13811, 13817, 13835, 13850, 13868, 13904, 13925, 13955, 13961, 13970, 14060, 14087, 14093, 14117, 14138, 14156, 14216, 14219, 14294, 14297, 14372, 14381, 14411, 14483, 14516, 14534, 14558, 14561, 14582, 14597, 14621, 14621, 14669, 14690, 14735, 14774, 14783, 14789, 14804, 14822, 14873, 14981, 14984, 14990, 15002, 15 12907, 12925, 13027, 13042, 13063, 13117, 13141, 13186, 13195, 13213, 13267, 13369, 13414, 13426, 13462, 14473, 14482, 14515, 14524, 14554, 14584, 14623, 14635, 14668, 15736, 15736, 15745, 15757, 15763, 15820, 15853, 15865, 15880, 15889, 15922, 16021, 16069, 16213, 16216, 16237, 16252, 16297, 16321, 16324, 16336, 16339, 16384, 16387, 16405, 16468, 16483, 16525, 16537, 16585], [2, 20, 29, 50, 176, 221, 332, 338, 356, 392, 440, 506, 539, 545, 593, 605, 620, 632, 692, 800, 806, 836, 866, 875, 962, 1019, 1061, 1097, 1166, 1169, 1223, 1940, 1946, 1952, 1976, 1982, 2180, 2201, 2216, 2228, 2243, 2288, 2303, 2363, 2390, 2399, 2402, 2411, 2420, 2429, 2480, 2504, 2513, 2549, 2585, 2597, 2642, 2654, 2666, 2684, 2693, 2726, 2738, 2756, 2762, 2771, 2780, 2798, 2843, 2912, 2942, 2990, 3032, 3044, 3059, 3086, 3122, 3140, 3191, 3194, 3212, 3227, 3275, 3311, 3314, 3362, 3392, 3422, 3590, 3632, 3641, 3665, 4061, 4061, 4112, 4172, 4181, 4229, 4232, 4349, 5801, 5804, 5828, 5846, 5849, 5870, 5873, 5945, 5954, 5966, 5987, 6125, 6179, 6206, 6212, 6218, 6269, 6281, 6344, 6473, 6476, 6482, 6527, 6572, 6575, 6614, 6620, 6629, 6656, 6659, 6707, 6755, 6758, 6809, 6845, 6851, 6974, 7106, 7121, 7124, 7187, 7205, 7217, 7220, 7355, 7421, 7454, 7532, 7550, 7580, 7625, 7661, 7679, 7721, 7730, 7736, 7754, 7793, 7889, 7907, 7919, 7925, 7931, 7970, 8042, 8087, 8093, 8147, 8153, 8225, 8237, 8255, 8288, 8294, 8309, 8312, 8321, 8597, 8627, 8696, 8708, 8756, 8783, 8786, 8843, 8861, 8879, 8927, 8951, 8966, 8969, 9065, 9089, 9095, 9101, 9104, 9137, 9146, 9206, 9209, 9215, 9233, 9260, 9320, 9446, 9473, 9485, 9563, 9572, 9578, 9596, 9602, 9605, 9611, 9617, 9677, 9680, 9701, 9722, 9779, 9794, 9824, 9872, 9896, 9935, 9947, 10034, 10055, 10100, 10277, 10307, 10457, 10532, 10574, 10616, 10625, 10691, 10802, 10838, 10901, 10994, 11009, 11027, 11120, 11138, 11144, 11210, 11228, 11237, 11240, 11261, 11372, 11378, 11462, 11465, 11468, 11474, 11480, 11492, 11567, 11582, 11591, 11606, 11627, 11645, 11684, 11687, 11738, 11753, 11765, 11825, 11888, 11912, 12011, 12026, 12071, 12074, 12095, 12098, 12101, 12125, 12173, 12182, 12191, 12245, 12248, 12272, 12275, 12296, 12437, 12461, 12518, 12599, 12608, 12677, 12692, 12854, 12866, 12875, 12899, 12938, 13055, 13079, 13142, 13307, 13316, 13328, 13331, 13424, 13457, 13478, 13538, 13562, 13583, 13601, 13736, 13760, 13805, 13811, 13817, 13835, 13850, 13868, 13904, 13925, 13955, 13961, 13970, 14060, 14087, 14093, 14117, 14138, 14156, 14216, 14219, 14294, 14297, 14372, 14381, 14411, 14483, 14516, 14534, 14558, 14561, 14582, 14597, 14621, 14621, 14669, 14690, 14735, 14774, 14783, 14789, 14804, 14822, 14873, 14981, 14984, 14990, 15002, 15056, 15062, 15179, 15224, 15248, 15257, 15287, 15314, 15320, 15350, 15440, 15458, 15482, 15497, 15512, 15530, 15539, 15551, 15575, 15614, 15680, 15716, 15737, 15746, 15779, 15812, 15827, 15881, 15911, 15950, 15965, 15968, 15971, 15977, 15980, 16001, 16022, 16034, 16064, 16067, 16109, 16160, 16169, 16217, 16262, 16424, 16484, 16532, 16547], [1092, 1101, 1167, 1170, 1176, 1179, 1269, 1296, 1332, 1335, 1359, 1398, 1416, 1425, 1461, 1506, 1509, 1596, 1614, 1632, 1656, 1674, 1677, 1686, 1764, 1785, 1878, 1896, 1923, 1941, 1944, 1956, 1962, 1968, 2076, 2097, 2100, 2142, 2148, 2217, 2292, 2364, 2373, 2430, 2475, 2481, 2538, 2550, 2565, 2568, 2616, 2643, 2661, 2781, 3639, 3639, 3648, 3654, 3708, 3711, 3720, 3765, 3792, 3795, 3846, 3999, 4020, 4038, 4047, 4062, 4062, 4065, 4074, 4425, 4452, 4470, 4515, 4545, 4590, 4620, 4647, 4650, 4656, 4719, 4746, 4767, 4782, 4812, 4884, 4905, 5025, 5109, 5130, 5136, 5151, 5160, 5172, 5208, 5229, 5235, 5277, 5295, 5304, 5313, 5316, 5328, 5361, 5370, 5385, 5409, 5454, 5484, 5487, 5550, 5559, 5562, 5601, 5607, 5658, 5661, 5730, 5781, 5802, 5847, 5853, 5871, 5877, 5886, 5904, 5952, 5988, 7863, 7875, 7926, 8013, 8070, 8208, 8214, 8220, 8307, 8358, 8406, 8448, 9597, 9618, 9633, 9648, 9675, 9714, 9786, 9807, 9831, 9954, 9972, 10167, 10218, 10227, 10275, 10308, 10332, 10341, 10368, 10389, 10410, 10422, 10428, 10521, 10596, 10605, 10611, 10617, 10635, 10659, 10758, 10869, 10884, 10911, 10923, 10956, 10992, 10998, 11052, 11103, 11154, 11238, 11340, 11343, 11400, 11427, 11643, 11652, 11664, 11697, 11727, 11847, 11850, 11946, 11967, 11976, 12051, 12060, 12072, 12198, 12255, 12294, 12312, 12330, 12351, 12441, 12540, 12549, 12597, 12612, 12618, 12621, 12690, 12723, 12774, 12804, 12873, 12900, 12912, 12918, 12945, 12954, 12993, 13059, 13080, 13116, 13122, 13158, 13215, 13236, 13260, 13275, 13326, 13383, 13389, 13425, 13437, 13476, 13602, 13623, 13668, 13677, 13689, 13692, 13806, 13818, 13869, 13875, 13956, 13992, 14013, 14025, 14091, 14097, 14124, 14133, 14145, 14151, 14157, 14166, 14169, 14196, 14205, 14481, 14502, 14529, 14553, 14622, 14625, 14673, 14736, 14784, 14790, 14796, 14886, 14910, 14943, 15051, 15057, 15069, 15135, 15180, 15183, 15189, 15198, 15249, 15369, 15441, 15444, 15462, 15492, 15507, 15609, 15618, 15738, 15738, 15750, 15810, 15861, 15870, 15885, 15915, 15981, 16008, 16041, 16062]], (0,))

  └ @ Emma /opt/Emma/src/cmd.jl:115

This happened on 3 out of 51 of the samples that i ran through EMMA.
Is there a way to troubleshoot this error?
Thanks, Tyler

**Comment by ian-small** [comment]
Fixed in f1cfe56
